// All photos organized by category (from /works/photo/[folder]/ folder)
export const photoSources: Record<string, { src: string; alt: string }[]> = {
  "womens-clothing": [
    { src: "/works/photo/womens-clothing/womens-clothing_1.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_2.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_3.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_4.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_5.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_6.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_7.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_8.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_9.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_11.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_12.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_13.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_14.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_15.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_16.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_17.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_18.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_19.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_20.jpg", alt: "Women's clothing product photography" },
    { src: "/works/photo/womens-clothing/womens-clothing_21.jpg", alt: "Women's clothing product photography" },
  ],
  "womens-fashion": [
    { src: "/works/photo/womens-fashion/womens-fashion_1.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_2.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_3.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_4.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_5.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_6.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_7.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_8.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_9.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_11.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_12.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_13.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_14.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_15.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_16.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_17.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_18.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_19.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_20.jpg", alt: "Women's fashion photography" },
    { src: "/works/photo/womens-fashion/womens-fashion_21.jpg", alt: "Women's fashion photography" },
  ],
  "mens": [
    { src: "/works/photo/mens/mens_1.jpg", alt: "Men's fashion photography" },
    { src: "/works/photo/mens/mens_2.jpg", alt: "Men's fashion photography" },
    { src: "/works/photo/mens/mens_4.jpg", alt: "Men's fashion photography" },
    { src: "/works/photo/mens/mens_5.jpg", alt: "Men's fashion photography" },
    { src: "/works/photo/mens/mens_6.jpg", alt: "Men's fashion photography" },
    { src: "/works/photo/mens/mens_7.jpg", alt: "Men's fashion photography" },
    { src: "/works/photo/mens/mens_8.jpg", alt: "Men's fashion photography" },
    { src: "/works/photo/mens/mens_9.jpg", alt: "Men's fashion photography" },
    { src: "/works/photo/mens/mens_10.jpg", alt: "Men's fashion photography" },
    { src: "/works/photo/mens/mens_11.jpg", alt: "Men's fashion photography" },
    { src: "/works/photo/mens/mens_12.jpg", alt: "Men's fashion photography" },
  ],
  "kids": [
    { src: "/works/photo/kids/kids_1.jpg", alt: "Kids and toys photography" },
    { src: "/works/photo/kids/kids_2.jpg", alt: "Kids and toys photography" },
    { src: "/works/photo/kids/kids_3.jpg", alt: "Kids and toys photography" },
    { src: "/works/photo/kids/kids_4.jpg", alt: "Kids and toys photography" },
    { src: "/works/photo/kids/kids_5.jpg", alt: "Kids and toys photography" },
    { src: "/works/photo/kids/kids_7.jpg", alt: "Kids and toys photography" },
    { src: "/works/photo/kids/kids_8.jpg", alt: "Kids and toys photography" },
    { src: "/works/photo/kids/kids_9.jpg", alt: "Kids and toys photography" },
    { src: "/works/photo/kids/kids_10.jpg", alt: "Kids and toys photography" },
    { src: "/works/photo/kids/kids_11.jpg", alt: "Kids and toys photography" },
    { src: "/works/photo/kids/kids_12.jpg", alt: "Kids and toys photography" },
    { src: "/works/photo/kids/kids_13.jpg", alt: "Kids and toys photography" },
  ],
  "accessories": [
    { src: "/works/photo/accessories/accessories_1.jpg", alt: "Accessories photography" },
    { src: "/works/photo/accessories/accessories_2.jpg", alt: "Accessories photography" },
    { src: "/works/photo/accessories/accessories_3.jpg", alt: "Accessories photography" },
    { src: "/works/photo/accessories/accessories_4.jpg", alt: "Accessories photography" },
    { src: "/works/photo/accessories/accessories_5.jpg", alt: "Accessories photography" },
    { src: "/works/photo/accessories/accessories_6.jpg", alt: "Accessories photography" },
    { src: "/works/photo/accessories/accessories_7.jpg", alt: "Accessories photography" },
    { src: "/works/photo/accessories/accessories_8.jpg", alt: "Accessories photography" },
    { src: "/works/photo/accessories/accessories_9.jpg", alt: "Accessories photography" },
  ],
  "products": [
    { src: "/works/photo/products/products_1.jpg", alt: "Products photography" },
    { src: "/works/photo/products/products_2.jpg", alt: "Products photography" },
    { src: "/works/photo/products/products_3.jpg", alt: "Products photography" },
    { src: "/works/photo/products/products_4.jpg", alt: "Products photography" },
    { src: "/works/photo/products/products_5.jpg", alt: "Products photography" },
  ],
  "sports": [
    { src: "/works/photo/sports/sports_1.jpg", alt: "Sports photography" },
    { src: "/works/photo/sports/sports_2.jpg", alt: "Sports photography" },
    { src: "/works/photo/sports/sports_3.jpg", alt: "Sports photography" },
    { src: "/works/photo/sports/sports_4.jpg", alt: "Sports photography" },
    { src: "/works/photo/sports/sports_5.jpg", alt: "Sports photography" },
  ],
  "womens-underwear": [
    { src: "/works/photo/womens-underwear/womens-underwear_1.jpg", alt: "Women's underwear photography" },
    { src: "/works/photo/womens-underwear/womens-underwear_2.jpg", alt: "Women's underwear photography" },
    { src: "/works/photo/womens-underwear/womens-underwear_4.jpg", alt: "Women's underwear photography" },
    { src: "/works/photo/womens-underwear/womens-underwear_5.jpg", alt: "Women's underwear photography" },
    { src: "/works/photo/womens-underwear/womens-underwear_6.jpg", alt: "Women's underwear photography" },
  ],
  "other": [
    { src: "/works/photo/other/other_1.jpg", alt: "Home and lifestyle photography" },
    { src: "/works/photo/other/other_7.jpg", alt: "Home and lifestyle photography" },
    { src: "/works/photo/other/other_8.jpg", alt: "Home and lifestyle photography" },
  ],
};