import type { Metadata } from "next";
import Link from "next/link";
import Header from "@/components/header";
import Footer from "@/components/footer";
import CtaButton from "@/components/cta-button";
import GalleryLightbox from "@/components/gallery-lightbox";
import ServiceFaq from "@/components/service-faq";

export const metadata: Metadata = {
  title: "Amazon Product Video Production — AI Video for Amazon Listings | FlarePix",
  description:
    "AI video for Amazon listings — generated by our professional team, not a self-serve tool. We handle the production so your product video looks professional and converts.",
  alternates: { canonical: "https://flarepix.com/services/ai-video" },
  openGraph: {
    title: "AI Product Video Production for Amazon — Professional Team | FlarePix",
    description:
      "AI video for Amazon listings — generated by our professional team, not a self-serve tool.",
    url: "https://flarepix.com/services/ai-video",
    type: "website",
    images: [{ url: "/og-image.jpg", width: 1200, height: 630, alt: "AI Product Video Production for Amazon" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Product Video Production for Amazon | FlarePix",
    description:
      "AI video for Amazon — generated by our professional team, not a self-serve tool.",
    images: ["/og-image.jpg"],
  },
};

const aiVideos = [
  { src: "/works/ai/videos/ai-video-01.mp4", title: "AI product animation" },
  { src: "/works/ai/videos/ai-video-02.mp4", title: "AI scene generation" },
  { src: "/works/ai/videos/ai-video-03.mp4", title: "AI social video" },
  { src: "/works/ai/videos/ai-video-04.mp4", title: "AI product video" },
];

const videoObjectSchema = {
  "@context": "https://schema.org",
  "@type": "VideoObject",
  name: "AI Product Video Production — FlarePix",
  description:
    "Professional AI-assisted product video production for Amazon sellers and ecommerce brands. Our team generates, reviews, and delivers AI videos that meet professional standards.",
  thumbnailUrl: "https://media.flarepix.com/works/posters/ai-video.jpg",
  uploadDate: "2026-01-15T00:00:00Z",
};

const howToSchema = {
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to Get an AI Product Video for Amazon",
  description:
    "Step-by-step guide to commissioning an AI product video from FlarePix — from brief to delivery.",
  step: [
    {
      "@type": "HowToStep",
      name: "Send your brief",
      text: "Contact us with your product details, target Amazon listing, and intended use — A+ content, social ad, or hero video. We'll respond within 24 hours.",
    },
    {
      "@type": "HowToStep",
      name: "We generate the video",
      text: "Our team uses AI production tools to generate video content from your reference assets. We manage prompts, reference curation, and generation settings — you don't touch any tool.",
    },
    {
      "@type": "HowToStep",
      name: "Human quality review",
      text: "Every AI output goes through professional review — product accuracy, visual quality, and brand consistency checked before delivery.",
    },
    {
      "@type": "HowToStep",
      name: "Receive your files",
      text: "Final files delivered in Amazon-ready formats, formatted for upload to your listing or ad platform.",
    },
  ],
};

const aiVideoFaqs = [
  {
    q: "Does AI video look AI-generated?",
    a: "Without professional oversight, yes — AI-generated video often has telltale signs: unnatural motion, visual artifacts, generic-looking scenes. FlarePix runs every AI output through human quality review before delivery. We fix artifacts, correct product angles, and ensure the final video looks professional on your Amazon listing.",
  },
  {
    q: "What's included in your human quality review?",
    a: "Every AI video we produce is reviewed by a team member before delivery. That means checking product accuracy, visual quality, brand consistency, and Amazon compliance. You receive finished files — not a draft to review and send back.",
  },
  {
    q: "What's the difference between AI video and brand film production?",
    a: "AI video is generated from reference assets — fast, scalable, and suited for batch content (Amazon A+ video, social ad variants, display campaigns). Brand film production involves a real shoot with professional talent, creative direction, and a multi-week post-production process. Brand films are built for your biggest launches and highest-stakes visual moments.",
  },
  {
    q: "What file formats do you deliver?",
    a: "We deliver MP4 and MOV files in standard Amazon, TikTok, and Instagram specs — optimised for upload to your listing, ad platform, or social channel. No conversion needed on your end.",
  },
  {
    q: "How long does AI video production take?",
    a: "Standard turnaround is 6–8 business days. For AI video specifically, turnaround can be faster depending on volume — often 3–5 business days for a single video. Rush delivery available.",
  },
];

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: aiVideoFaqs.map((f) => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: { "@type": "Answer", text: f.a },
  })),
};

export default function AiVideoPage() {
  return (
    <>
      <Header />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify([videoObjectSchema, howToSchema, faqSchema]) }}
      />
      <main className="mx-auto max-w-7xl px-6 py-24">
        <Link
          href="/services#ai-video"
          className="text-sm text-[var(--muted)] hover:text-[var(--foreground)] transition-colors"
        >
          &larr; All services
        </Link>

        <h1 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">
          AI Product Video
        </h1>
        <p className="mt-4 max-w-2xl text-lg text-[var(--muted)]">
          AI-generated product videos — produced by our professional team, not a
          self-serve tool. We manage the entire process: generation, quality
          control, and delivery — so you get a video that actually represents
          your product well on Amazon.
        </p>

        <div className="mt-6 flex gap-4">
          <CtaButton href="/contact">Get a quote</CtaButton>
        </div>

        {/* Video gallery */}
        <section className="mt-16">
          <h2 className="text-xl font-semibold">AI video examples</h2>
          <GalleryLightbox
            items={aiVideos.map((v) => ({ src: v.src, type: "video" as const, title: v.title }))}
            columns={2}
          />
        </section>

        {/* SEO content */}
        <section className="mt-16">
          <h2 className="text-xl font-semibold">What is AI product video — and why it&apos;s not a self-serve tool</h2>
          <div className="mt-6 grid gap-8 sm:grid-cols-2">
            <div>
              <p className="text-[var(--muted)]">
                Most AI video tools are sold as self-serve products: upload your product image, click generate, download a video. The problem is that approach produces generic-looking content — and when every seller using the same tool outputs the same style, your listing looks exactly like your competitor&apos;s.
              </p>
              <p className="mt-4 text-[var(--muted)]">
                The truth about AI video: the model outputs are only as good as the prompts, the reference assets, and the quality review applied by someone who understands what &ldquo;professional&rdquo; looks like on an Amazon listing. Without that human layer, you get motion that feels artificial, product angles that don&apos;t showcase real value, and visual artifacts that hurt credibility.
              </p>
              <p className="mt-4 text-[var(--muted)]">
                FlarePix runs AI generation as a managed production service. We handle prompt design, reference material curation, and human QC on every output. You receive a finished video ready for your listing — not a file to experiment with.
              </p>
            </div>
            <div>
              <p className="font-medium text-[var(--foreground)]">Where AI video works for Amazon sellers</p>
              <ul className="mt-4 space-y-3 text-[var(--muted)]">
                <li className="flex items-start gap-2">
                  <span className="mt-1.5 h-1.5 w-1.5 flex-none rounded-full bg-[var(--amber)]" />
                  <span><strong>Amazon A+ video</strong> — Video on detail pages lifts conversion, but only when the quality matches your product. AI video at scale, with QC, fills this gap.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="mt-1.5 h-1.5 w-1.5 flex-none rounded-full bg-[var(--amber)]" />
                  <span><strong>Social and display ads</strong> — Batch-generate creative variants for Meta, TikTok, and Google — each reviewed before delivery.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="mt-1.5 h-1.5 w-1.5 flex-none rounded-full bg-[var(--amber)]" />
                  <span><strong>Retail and wholesale pitch</strong> — Visual assets for buyer meetings and retailer submissions — fast turnaround that fits launch timelines.</span>
                </li>
                <li className="flex items-start gap-2">
                  <span className="mt-1.5 h-1.5 w-1.5 flex-none rounded-full bg-[var(--amber)]" />
                  <span><strong>Email and newsletter content</strong> — Product video embedded in email campaigns drives engagement that static images can&apos;t match.</span>
                </li>
              </ul>
            </div>
          </div>
        </section>

        <div className="mt-16 rounded-2xl border border-dashed border-black/[0.10] bg-[var(--surface)] p-8 text-center">
          <p className="text-[var(--muted)]">
            More AI video examples coming soon.
          </p>
        </div>

        {/* Cross-links to related services */}
        <section className="mt-16 grid gap-4 sm:grid-cols-2">
          <Link
            href="/services/ai-imagery"
            className="group rounded-xl border border-black/[0.08] bg-[var(--surface)] p-6 hover:border-[var(--amber)] transition-colors"
          >
            <p className="text-sm text-[var(--muted)]">Pair with</p>
            <p className="mt-1 font-semibold group-hover:text-[var(--amber)] transition-colors">
              AI Imagery →
            </p>
            <p className="mt-1 text-sm text-[var(--muted)]">
              Generate lifestyle images to go with your video content.
            </p>
          </Link>
          <Link
            href="/services/brand-film"
            className="group rounded-xl border border-black/[0.08] bg-[var(--surface)] p-6 hover:border-[var(--amber)] transition-colors"
          >
            <p className="text-sm text-[var(--muted)]">Looking for something bigger?</p>
            <p className="mt-1 font-semibold group-hover:text-[var(--amber)] transition-colors">
              Brand Film Production →
            </p>
            <p className="mt-1 text-sm text-[var(--muted)]">
              Cinematic brand films for hero product launches.
            </p>
          </Link>
        </section>

        <ServiceFaq faqs={aiVideoFaqs} />
      </main>
      <Footer />
    </>
  );
}
